/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app.vue",
    "./pages/**/*.vue",
    "./components/**/*.vue",
  ],
  theme: {
    extend: {
      colors: {
        // Cozina Marray Theme
        "cm-surface": "#131313",
        "cm-surface-dim": "#131313",
        "cm-surface-bright": "#3a3939",
        "cm-outline": "#aa8986",
        "cm-on-secondary-fixed": "#2c1600",
        "cm-inverse-surface": "#e5e2e1",
        "cm-tertiary-container": "#646565",
        "cm-on-secondary-fixed-variant": "#623f18",
        "cm-surface-container-low": "#1c1b1b",
        "cm-surface-variant": "#353534",
        "cm-tertiary-fixed": "#e2e2e2",
        "cm-surface-container": "#201f1f",
        "cm-on-primary-fixed": "#410004",
        "cm-on-error-container": "#ffdad6",
        "cm-primary-fixed-dim": "#ffb3ae",
        "cm-tertiary": "#c6c6c7",
        "cm-secondary-fixed-dim": "#f0bd8b",
        "cm-on-surface-variant": "#e3bebb",
        "cm-on-background": "#e5e2e1",
        "cm-primary-fixed": "#ffdad7",
        "cm-surface-container-high": "#2a2a2a",
        "cm-outline-variant": "#5a403e",
        "cm-tertiary-fixed-dim": "#c6c6c7",
        "cm-on-primary-fixed-variant": "#930015",
        "cm-on-primary": "#68000b",
        "cm-on-surface": "#e5e2e1",
        "cm-secondary": "#f0bd8b",
        "cm-on-tertiary": "#2f3131",
        "cm-secondary-container": "#65411a",
        "cm-primary-container": "#c1272d",
        "cm-surface-container-highest": "#353534",
        "cm-on-primary-container": "#ffdbd8",
        "cm-on-secondary": "#482904",
        "cm-error": "#ffb4ab",
        "cm-on-tertiary-fixed": "#1a1c1c",
        "cm-on-secondary-container": "#e1af7e",
        "cm-on-tertiary-container": "#e3e3e3",
        "cm-background": "#131313",
        "cm-inverse-on-surface": "#313030",
        "cm-primary": "#ffb3ae",
        "cm-on-error": "#690005",
        "cm-secondary-fixed": "#ffdcbd",
        "cm-surface-tint": "#ffb3ae",
        "cm-surface-container-lowest": "#0e0e0e",
        "cm-inverse-primary": "#b71f27",
        "cm-error-container": "#93000a",
        "cm-on-tertiary-fixed-variant": "#454747"
      },
      fontFamily: {
        "cm-headline": ["Space Grotesk"],
        "cm-body": ["Inter"],
        "cm-label": ["Inter"]
      },
      borderRadius: {
        "cm-DEFAULT": "0.125rem",
        "cm-lg": "0.25rem",
        "cm-xl": "0.5rem",
        "cm-full": "0.75rem"
      },
    },
  },
  plugins: [],
}
